'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.42000
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class resLang
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NetFilter.resLang", GetType(resLang).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        '''  재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  ADD과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property APPEND() As String
            Get
                Return ResourceManager.GetString("APPEND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  APPLIED과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property APPLIED() As String
            Get
                Return ResourceManager.GetString("APPLIED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  APPLY과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property APPLY() As String
            Get
                Return ResourceManager.GetString("APPLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Change Language:과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property CHANGELANG() As String
            Get
                Return ResourceManager.GetString("CHANGELANG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  EDITING과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property EDITING() As String
            Get
                Return ResourceManager.GetString("EDITING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Same item already exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property ERR_EXISTING_VALUE() As String
            Get
                Return ResourceManager.GetString("ERR_EXISTING_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  The program was run for the first time or the configuration file is invalid. Initializing the configuration file.과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property ERR_INVALID_CONFIG() As String
            Get
                Return ResourceManager.GetString("ERR_INVALID_CONFIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please enter a value.과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property ERR_NO_VALUE() As String
            Get
                Return ResourceManager.GetString("ERR_NO_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please select the item to be deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property ERR_NOTHING_SELECTED_TO_DELETE() As String
            Get
                Return ResourceManager.GetString("ERR_NOTHING_SELECTED_TO_DELETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Blocking is maintained even if the program is terminated by modifying system files.
        '''After changing and applying the blocked sites, please restart your browser, etc.과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property INFO_GEN_1() As String
            Get
                Return ResourceManager.GetString("INFO_GEN_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please enter a site to block (e.g.: www.youtube.com, Note: We are not responsible for damage caused by entering an invalid site address.)과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property INFO_GEN_2() As String
            Get
                Return ResourceManager.GetString("INFO_GEN_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Be sure to click the Apply button and exit.과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property INFO_WARN_1() As String
            Get
                Return ResourceManager.GetString("INFO_WARN_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  English과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property LANGEN() As String
            Get
                Return ResourceManager.GetString("LANGEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  한국어과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property LANGKR() As String
            Get
                Return ResourceManager.GetString("LANGKR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  NETFILTER과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property PGNAME() As String
            Get
                Return ResourceManager.GetString("PGNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  QUIT과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property QUIT() As String
            Get
                Return ResourceManager.GetString("QUIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  UNBLOCK SELECTED SITE과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property UNBLOCK() As String
            Get
                Return ResourceManager.GetString("UNBLOCK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  v0.3과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Public Shared ReadOnly Property VERSTR() As String
            Get
                Return ResourceManager.GetString("VERSTR", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
