name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build:
    needs: test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Archive and Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: build-result
        path: D:\a\Netfilter\Netfilter\NetFilter\bin\Debug\net5.0-windows
        
  publish:
    needs: test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
#    - name: Publish
#      uses: brandedoutcast/publish-nuget@v2.5.2
#      with:
#        PROJECT_FILE_PATH: Netfilter\Netfilter.vbproj
#        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
